#include "http/api_router.hpp"
#include <cctype>
#include <cstdlib>
#include <sstream>
namespace tsto { namespace {
std::string json_escape(const std::string& s){std::string o;for(char c:s){switch(c){case '"':o+="\\\"";break;case '\\':o+="\\\\";break;case '\n':o+="\\n";break;case '\r':o+="\\r";break;default:o+=c;}}return o;}
std::string field(const std::string& json,const std::string& key){auto p=json.find("\""+key+"\"");if(p==std::string::npos)return{};p=json.find(':',p);if(p==std::string::npos)return{};++p;while(p<json.size()&&std::isspace(static_cast<unsigned char>(json[p])))++p;if(p<json.size()&&json[p]=='"'){++p;std::string v;bool escape=false;for(;p<json.size();++p){if(escape){v+=json[p];escape=false;}else if(json[p]=='\\')escape=true;else if(json[p]=='"')break;else v+=json[p];}return v;}auto end=json.find_first_of(",}",p);return json.substr(p,end==std::string::npos?json.size()-p:end-p);}
HttpResponse error(int status,const std::string& message){return {status,"{\"error\":\""+json_escape(message)+"\"}"};}
}
ApiRouter::ApiRouter(AuthService&a,TownService&t):auth_(a),towns_(t){}
HttpResponse ApiRouter::handle(const HttpRequest&r){try{if(r.method=="POST"&&r.path=="/v1/auth/register"){auto x=auth_.register_account(field(r.body,"email"),field(r.body,"password"),field(r.body,"display_name"),field(r.body,"device_id"));return {201,"{\"account_id\":"+std::to_string(x.account.id)+",\"token\":\""+x.access_token+"\"}"};}if(r.method=="POST"&&r.path=="/v1/auth/login"){auto x=auth_.login(field(r.body,"email"),field(r.body,"password"),field(r.body,"device_id"));return {200,"{\"account_id\":"+std::to_string(x.account.id)+",\"token\":\""+x.access_token+"\"}"};}auto session=auth_.authenticate(r.authorization);if(r.method=="POST"&&r.path=="/v1/devices"){auto id=field(r.body,"device_id");if(id.empty()||!auth_.authenticate(r.authorization).account_id)return error(400,"device_id_required");return {200,"{\"registered\":"+(std::string(db_placeholder="true"))+"}"};}if(r.method=="GET"&&r.path=="/v1/town"){auto t=towns_.load(session.account_id);return {200,"{\"revision\":"+std::to_string(t.revision)+",\"payload\":\""+json_escape(t.payload)+"\"}"};}if(r.method=="PUT"&&r.path=="/v1/town"){auto rev=std::stoll(field(r.body,"expected_revision"));auto t=towns_.save(session.account_id,rev,field(r.body,"payload"));return {200,"{\"revision\":"+std::to_string(t.revision)+"}"};}return error(404,"not_found");}catch(const TownConflict&){return error(409,"revision_conflict");}catch(const std::invalid_argument&e){return error(400,e.what());}catch(const std::exception&e){return error(401,e.what());}}
}
