#include "database/database.hpp"
#include <sqlite3.h>
#include <fstream>
#include <stdexcept>
#include <chrono>
#include <sstream>

namespace tsto {
namespace { void check(int rc, sqlite3* db, const char* what){ if(rc!=SQLITE_OK&&rc!=SQLITE_DONE&&rc!=SQLITE_ROW) throw std::runtime_error(std::string(what)+": "+sqlite3_errmsg(db)); }
std::int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
void bind_text(sqlite3_stmt* s,int n,const std::string& v){check(sqlite3_bind_text(s,n,v.c_str(),-1,SQLITE_TRANSIENT),sqlite3_db_handle(s),"bind");}
}
Database::Database(const std::filesystem::path& p){if(!p.parent_path().empty())std::filesystem::create_directories(p.parent_path());if(sqlite3_open_v2(p.string().c_str(),&db_,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX)!=SQLITE_OK)throw std::runtime_error("SQLite open failed");exec("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;");}
Database::~Database(){if(db_)sqlite3_close(db_);}
void Database::exec(const std::string& q)const{char* e=nullptr;if(sqlite3_exec(db_,q.c_str(),nullptr,nullptr,&e)!=SQLITE_OK){std::string x=e?e:"SQLite error";sqlite3_free(e);throw std::runtime_error(x);}}
void Database::migrate(){std::ifstream f("migrations/001_initial.sql");if(!f)throw std::runtime_error("Migration file missing");exec(std::string((std::istreambuf_iterator<char>(f)),{}));}
std::optional<Account> Database::find_account_by_email(const std::string& email)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"SELECT id,email,password_hash,display_name,user_id,mayhem_id FROM accounts WHERE email=? COLLATE NOCASE",-1,&s,nullptr),db_,"prepare");bind_text(s,1,email);auto rc=sqlite3_step(s);std::optional<Account> a;if(rc==SQLITE_ROW)a=Account{sqlite3_column_int64(s,0),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),reinterpret_cast<const char*>(sqlite3_column_text(s,3)),reinterpret_cast<const char*>(sqlite3_column_text(s,4)),sqlite3_column_int64(s,5)};sqlite3_finalize(s);return a;}
std::optional<Account> Database::find_account_by_id(std::int64_t id)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"SELECT id,email,password_hash,display_name,user_id,mayhem_id FROM accounts WHERE id=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,id);auto rc=sqlite3_step(s);std::optional<Account>a;if(rc==SQLITE_ROW)a=Account{sqlite3_column_int64(s,0),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),reinterpret_cast<const char*>(sqlite3_column_text(s,3)),reinterpret_cast<const char*>(sqlite3_column_text(s,4)),sqlite3_column_int64(s,5)};sqlite3_finalize(s);return a;}
std::optional<Account> Database::create_account(const Account&a){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"INSERT INTO accounts(email,password_hash,display_name,user_id,mayhem_id) VALUES(?,?,?,?,?)",-1,&s,nullptr),db_,"prepare");bind_text(s,1,a.email);bind_text(s,2,a.password_hash);bind_text(s,3,a.display_name);bind_text(s,4,a.user_id);sqlite3_bind_int64(s,5,a.mayhem_id);auto rc=sqlite3_step(s);sqlite3_finalize(s);if(rc!=SQLITE_DONE)return std::nullopt;return find_account_by_id(sqlite3_last_insert_rowid(db_));}
bool Database::add_device(const Device&d){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"INSERT INTO devices(id,account_id,platform,app_version,last_seen_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,platform=excluded.platform,app_version=excluded.app_version,last_seen_at=CURRENT_TIMESTAMP",-1,&s,nullptr),db_,"prepare");bind_text(s,1,d.id);sqlite3_bind_int64(s,2,d.account_id);bind_text(s,3,d.platform);bind_text(s,4,d.app_version);auto rc=sqlite3_step(s);sqlite3_finalize(s);return rc==SQLITE_DONE;}
bool Database::device_belongs_to(std::int64_t id,const std::string& device)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"SELECT 1 FROM devices WHERE id=? AND account_id=?",-1,&s,nullptr),db_,"prepare");bind_text(s,1,device);sqlite3_bind_int64(s,2,id);auto ok=sqlite3_step(s)==SQLITE_ROW;sqlite3_finalize(s);return ok;}
bool Database::create_session(const Session&x){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"INSERT INTO sessions(token_hash,account_id,device_id,expires_at) VALUES(?,?,?,?)",-1,&s,nullptr),db_,"prepare");bind_text(s,1,x.token_hash);sqlite3_bind_int64(s,2,x.account_id);bind_text(s,3,x.device_id);bind_text(s,4,x.expires_at);auto rc=sqlite3_step(s);sqlite3_finalize(s);return rc==SQLITE_DONE;}
std::optional<Session> Database::find_session(const std::string&hash)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"SELECT token_hash,account_id,device_id,expires_at FROM sessions WHERE token_hash=? AND CAST(expires_at AS INTEGER)>?",-1,&s,nullptr),db_,"prepare");bind_text(s,1,hash);sqlite3_bind_int64(s,2,now());auto rc=sqlite3_step(s);std::optional<Session>x;if(rc==SQLITE_ROW)x=Session{reinterpret_cast<const char*>(sqlite3_column_text(s,0)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),sqlite3_column_int64(s,1),reinterpret_cast<const char*>(sqlite3_column_text(s,3))};sqlite3_finalize(s);return x;}
void Database::delete_expired_sessions(){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"DELETE FROM sessions WHERE CAST(expires_at AS INTEGER)<=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,now());check(sqlite3_step(s),db_,"delete");sqlite3_finalize(s);}
std::optional<Town> Database::get_town(std::int64_t id)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"SELECT account_id,payload,revision,updated_at FROM towns WHERE account_id=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,id);auto rc=sqlite3_step(s);std::optional<Town>t;if(rc==SQLITE_ROW)t=Town{sqlite3_column_int64(s,0),std::string(reinterpret_cast<const char*>(sqlite3_column_blob(s,1)),sqlite3_column_bytes(s,1)),sqlite3_column_int64(s,2),reinterpret_cast<const char*>(sqlite3_column_text(s,3))};sqlite3_finalize(s);return t;}
bool Database::save_town(const Town&e,const std::string&backup){std::lock_guard l(mutex_);exec("BEGIN IMMEDIATE");try{sqlite3_stmt*s=nullptr;check(sqlite3_prepare_v2(db_,"INSERT INTO towns(account_id,payload,revision) VALUES(?,?,?) ON CONFLICT(account_id) DO UPDATE SET payload=excluded.payload,revision=excluded.revision,updated_at=CURRENT_TIMESTAMP WHERE towns.revision=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,e.account_id);sqlite3_bind_blob(s,2,e.payload.data(),static_cast<int>(e.payload.size()),SQLITE_TRANSIENT);sqlite3_bind_int64(s,3,e.revision+1);sqlite3_bind_int64(s,4,e.revision);auto rc=sqlite3_step(s);sqlite3_finalize(s);if(rc!=SQLITE_DONE||sqlite3_changes(db_)==0){exec("ROLLBACK");return false;}if(!backup.empty()){check(sqlite3_prepare_v2(db_,"INSERT INTO town_backups(account_id,revision,payload) VALUES(?,?,?)",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,e.account_id);sqlite3_bind_int64(s,2,e.revision);sqlite3_bind_blob(s,3,backup.data(),static_cast<int>(backup.size()),SQLITE_TRANSIENT);check(sqlite3_step(s),db_,"backup");sqlite3_finalize(s);}exec("COMMIT");return true;}catch(...){exec("ROLLBACK");throw;}}
}
