#include "database/database.hpp"
#include <sqlite3.h>
#include <chrono>
#include <fstream>
#include <stdexcept>
namespace tsto { namespace {
void ok(int rc,sqlite3*db,const char*op){if(rc!=SQLITE_OK&&rc!=SQLITE_ROW&&rc!=SQLITE_DONE)throw std::runtime_error(std::string(op)+": "+sqlite3_errmsg(db));}
void bind(sqlite3_stmt*s,int i,const std::string&v){ok(sqlite3_bind_text(s,i,v.c_str(),-1,SQLITE_TRANSIENT),sqlite3_db_handle(s),"bind");}
std::string text(sqlite3_stmt*s,int i){auto*p=sqlite3_column_text(s,i);return p?reinterpret_cast<const char*>(p):"";}
std::int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
Account account(sqlite3_stmt*s){return {sqlite3_column_int64(s,0),text(s,1),text(s,2),text(s,3),text(s,4),sqlite3_column_int64(s,5)};}
}
Database::Database(const std::filesystem::path&p){if(!p.parent_path().empty())std::filesystem::create_directories(p.parent_path());if(sqlite3_open_v2(p.string().c_str(),&db_,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK)throw std::runtime_error("unable to open SQLite database");exec("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;");}
Database::~Database(){if(db_)sqlite3_close(db_);}
void Database::exec(const std::string&q)const{char*e=nullptr;if(sqlite3_exec(db_,q.c_str(),nullptr,nullptr,&e)!=SQLITE_OK){std::string m=e?e:"SQLite error";sqlite3_free(e);throw std::runtime_error(m);}}
void Database::migrate(){for(const char*name:{"migrations/001_initial.sql","migrations/002_player_currencies.sql"}){std::ifstream f(name);if(!f)throw std::runtime_error(std::string("migration missing: ")+name);exec({std::istreambuf_iterator<char>(f),{}});}}
std::optional<Account> Database::find_account_by_email(const std::string&e)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"SELECT id,email,password_hash,display_name,user_id,mayhem_id FROM accounts WHERE email=? COLLATE NOCASE",-1,&s,nullptr),db_,"prepare");bind(s,1,e);std::optional<Account>a;if(sqlite3_step(s)==SQLITE_ROW)a=account(s);sqlite3_finalize(s);return a;}
std::optional<Account> Database::find_account_by_id(std::int64_t id)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"SELECT id,email,password_hash,display_name,user_id,mayhem_id FROM accounts WHERE id=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,id);std::optional<Account>a;if(sqlite3_step(s)==SQLITE_ROW)a=account(s);sqlite3_finalize(s);return a;}
std::optional<Account> Database::create_account(const Account&a){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"INSERT INTO accounts(email,password_hash,display_name,user_id,mayhem_id) VALUES(?,?,?,?,?)",-1,&s,nullptr),db_,"prepare");bind(s,1,a.email);bind(s,2,a.password_hash);bind(s,3,a.display_name);bind(s,4,a.user_id);sqlite3_bind_int64(s,5,a.mayhem_id);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);return{};}sqlite3_finalize(s);return find_account_by_email(a.email);}
bool Database::add_device(const Device&d){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"INSERT INTO devices(id,account_id,platform,app_version) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,platform=excluded.platform,app_version=excluded.app_version,last_seen_at=CURRENT_TIMESTAMP",-1,&s,nullptr),db_,"prepare");bind(s,1,d.id);sqlite3_bind_int64(s,2,d.account_id);bind(s,3,d.platform);bind(s,4,d.app_version);bool r=sqlite3_step(s)==SQLITE_DONE;sqlite3_finalize(s);return r;}
bool Database::device_belongs_to(std::int64_t id,const std::string&d)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"SELECT 1 FROM devices WHERE account_id=? AND id=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,id);bind(s,2,d);bool r=sqlite3_step(s)==SQLITE_ROW;sqlite3_finalize(s);return r;}
bool Database::create_session(const Session&x){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"INSERT INTO sessions(token_hash,account_id,device_id,expires_at) VALUES(?,?,?,?)",-1,&s,nullptr),db_,"prepare");bind(s,1,x.token_hash);sqlite3_bind_int64(s,2,x.account_id);bind(s,3,x.device_id);bind(s,4,x.expires_at);bool r=sqlite3_step(s)==SQLITE_DONE;sqlite3_finalize(s);return r;}
std::optional<Session> Database::find_session(const std::string&h)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"SELECT token_hash,account_id,device_id,expires_at FROM sessions WHERE token_hash=? AND CAST(expires_at AS INTEGER)>?",-1,&s,nullptr),db_,"prepare");bind(s,1,h);sqlite3_bind_int64(s,2,now());std::optional<Session>x;if(sqlite3_step(s)==SQLITE_ROW)x=Session{text(s,0),text(s,2),sqlite3_column_int64(s,1),text(s,3)};sqlite3_finalize(s);return x;}
void Database::delete_expired_sessions(){std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"DELETE FROM sessions WHERE CAST(expires_at AS INTEGER)<=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,now());ok(sqlite3_step(s),db_,"delete");sqlite3_finalize(s);}
std::optional<Town> Database::get_town(std::int64_t id)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"SELECT account_id,payload,revision,updated_at FROM towns WHERE account_id=?",-1,&s,nullptr),db_,"prepare");sqlite3_bind_int64(s,1,id);std::optional<Town>t;if(sqlite3_step(s)==SQLITE_ROW){auto*p=sqlite3_column_blob(s,1);t=Town{sqlite3_column_int64(s,0),std::string(static_cast<const char*>(p),sqlite3_column_bytes(s,1)),sqlite3_column_int64(s,2),text(s,3)};}sqlite3_finalize(s);return t;}
bool Database::save_town(const Town&e,const std::string&backup){std::lock_guard l(mutex_);exec("BEGIN IMMEDIATE");try{auto c=get_town(e.account_id);if((c&&c->revision!=e.revision)||(!c&&e.revision!=0)){exec("ROLLBACK");return false;}sqlite3_stmt*s=nullptr;const char*q=c?"UPDATE towns SET payload=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE account_id=? AND revision=?":"INSERT INTO towns(account_id,payload,revision) VALUES(?,?,1)";ok(sqlite3_prepare_v2(db_,q,-1,&s,nullptr),db_,"prepare town save");sqlite3_bind_blob(s,1,e.payload.data(),static_cast<int>(e.payload.size()),SQLITE_TRANSIENT);sqlite3_bind_int64(s,2,e.account_id);if(c)sqlite3_bind_int64(s,3,e.revision);bool r=sqlite3_step(s)==SQLITE_DONE&&sqlite3_changes(db_)==1;sqlite3_finalize(s);if(!r){exec("ROLLBACK");return false;}if(!backup.empty()){ok(sqlite3_prepare_v2(db_,"INSERT INTO town_backups(account_id,revision,payload) VALUES(?,?,?)",-1,&s,nullptr),db_,"prepare backup");sqlite3_bind_int64(s,1,e.account_id);sqlite3_bind_int64(s,2,e.revision);sqlite3_bind_blob(s,3,backup.data(),static_cast<int>(backup.size()),SQLITE_TRANSIENT);ok(sqlite3_step(s),db_,"backup");sqlite3_finalize(s);}exec("COMMIT");return true;}catch(...){exec("ROLLBACK");throw;}}
std::map<std::string,std::int64_t> Database::get_currencies(std::int64_t id)const{std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"SELECT currency,amount FROM account_currencies WHERE account_id=? ORDER BY currency",-1,&s,nullptr),db_,"prepare currency read");sqlite3_bind_int64(s,1,id);std::map<std::string,std::int64_t>r;while(sqlite3_step(s)==SQLITE_ROW)r.emplace(text(s,0),sqlite3_column_int64(s,1));sqlite3_finalize(s);return r;}
bool Database::set_currency(std::int64_t id,const std::string&currency,std::int64_t amount){if(currency.empty()||amount<0)return false;std::lock_guard l(mutex_);sqlite3_stmt*s=nullptr;ok(sqlite3_prepare_v2(db_,"INSERT INTO account_currencies(account_id,currency,amount) VALUES(?,?,?) ON CONFLICT(account_id,currency) DO UPDATE SET amount=excluded.amount,updated_at=CURRENT_TIMESTAMP",-1,&s,nullptr),db_,"prepare currency write");sqlite3_bind_int64(s,1,id);bind(s,2,currency);sqlite3_bind_int64(s,3,amount);bool r=sqlite3_step(s)==SQLITE_DONE;sqlite3_finalize(s);return r;}
}
