#include "auth/auth_service.hpp"
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include <chrono>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <vector>
namespace tsto {namespace {std::string hex(const unsigned char*d,size_t n){std::ostringstream o;for(size_t i=0;i<n;++i)o<<std::hex<<std::setw(2)<<std::setfill('0')<<static_cast<unsigned>(d[i]);return o.str();}std::string random_hex(size_t n){std::vector<unsigned char>b(n);if(RAND_bytes(b.data(),static_cast<int>(n))!=1)throw std::runtime_error("secure random failed");return hex(b.data(),n);}std::string sha(const std::string&v){unsigned char d[SHA256_DIGEST_LENGTH];SHA256(reinterpret_cast<const unsigned char*>(v.data()),v.size(),d);return hex(d,sizeof d);}std::string hashpw(const std::string&p){auto salt=random_hex(16);unsigned char d[32];PKCS5_PBKDF2_HMAC(p.c_str(),static_cast<int>(p.size()),reinterpret_cast<const unsigned char*>(salt.data()),static_cast<int>(salt.size()),120000,EVP_sha256(),sizeof d,d);return "pbkdf2$120000$"+salt+"$"+hex(d,sizeof d);}bool checkpw(const std::string&p,const std::string&s){auto a=s.find('$'),b=s.find('$',a+1),c=s.find('$',b+1);if(a==std::string::npos||b==std::string::npos||c==std::string::npos)return false;unsigned char d[32];PKCS5_PBKDF2_HMAC(p.c_str(),static_cast<int>(p.size()),reinterpret_cast<const unsigned char*>(s.substr(b+1,c-b-1).data()),static_cast<int>(c-b-1),std::stoi(s.substr(a+1,b-a-1)),EVP_sha256(),sizeof d,d);return hex(d,sizeof d)==s.substr(c+1);}long long now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}}
AuthService::AuthService(Database&d,const Config&c):db_(d),config_(c){}
AuthResult AuthService::register_account(std::string e,std::string p,std::string n,std::string device){if(e.empty()||p.size()<8||device.empty())throw std::invalid_argument("email, device_id, and an 8-character password are required");if(db_.find_account_by_email(e))throw std::runtime_error("account already exists");auto a=db_.create_account(Account{0,e,hashpw(p),n,random_hex(16),now()});if(!a||!db_.add_device(Device{device,"unknown","",a->id}))throw std::runtime_error("account creation failed");return login(e,p,device);}
AuthResult AuthService::login(std::string e,std::string p,std::string device){auto a=db_.find_account_by_email(e);if(!a||!checkpw(p,a->password_hash))throw std::runtime_error("invalid credentials");if(!db_.device_belongs_to(a->id,device)&&!db_.add_device(Device{device,"unknown","",a->id}))throw std::runtime_error("device registration failed");auto token=random_hex(32);Session s{sha(token),device,a->id,std::to_string(now()+config_.session_ttl_seconds)};if(!db_.create_session(s))throw std::runtime_error("session creation failed");return {*a,s,token};}
void AuthService::register_device(const Session&s,std::string id,std::string p,std::string v){if(!db_.add_device(Device{std::move(id),std::move(p),std::move(v),s.account_id}))throw std::runtime_error("device registration failed");}
Session AuthService::authenticate(const std::string&h)const{if(h.rfind("Bearer ",0)!=0)throw std::runtime_error("bearer token required");auto s=db_.find_session(sha(h.substr(7)));if(!s||!db_.device_belongs_to(s->account_id,s->device_id))throw std::runtime_error("invalid or expired session");return*s;}
}
